In [1]:
                                               #THEORETICAL QUESTIONS



# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
#enhance Python's capabilities for numerical operations

#Purpose of NumPy
#Handling Arrays: Think of NumPy as a way to work with lists of numbers more effectively. 
# Instead of using regular lists, you can use NumPy arrays, which are designed specifically for numerical data.

#Mathematical Functions: NumPy comes with a lot of built-in math tools.
# You can do things like add, subtract, multiply, or find averages quickly and easily.

#Building Block: Many other libraries in data science, like Pandas for data manipulation or Matplotlib for plotting, rely on NumPy.
#  It acts as a foundation that makes these other tools work better.




#Advantages of NumPy
#Speed: NumPy is faster than regular Python when it comes to math. It can handle large amounts of data quickly,
#  which is great when you’re working with big datasets.
#Less Memory Usage: NumPy arrays use less memory compared to standard Python lists, 
# so you can store more data without slowing down your computer.
#Easy to Use: NumPy has a simple and clear syntax.
#  You can perform complex calculations with just a few lines of code, making your work easier.
#Smart Indexing: NumPy lets you access and manipulate data in clever ways.
#  You can easily grab specific parts of your data without a hassle.


In [2]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
#other?

#np.mean()
#This function calculates the average of all the numbers in a list or array.
#ex: 
x = [1,2,3,4,5]
import numpy as np
np.mean(x)

np.float64(3.0)

In [5]:
#np.average()
#his function also calculates an average,
#  but it has a special feature: you can give it weights. This means some numbers can count more than others.
#ex:
np.average(x , weights= [1,2,1,1,4])

np.float64(3.5555555555555554)

In [7]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays

#using 1d array

x = [1,2,3,4,5,5,6,6,7]
array1 = np.array(x)

In [11]:
array1[::-1]

array([7, 6, 6, 5, 5, 4, 3, 2, 1])

In [24]:

#using 2d array
 
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])



In [25]:
array_2d[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [26]:
array_2d[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [27]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
#in memory management and performance.

#We can determine the data type of elements using .dtype
array1.dtype

dtype('int64')

In [29]:
#Importance of Data Types
#1.Memory Management:
# Different data types consume different amounts of memory.
# For example, an int32 takes up 4 bytes, while an int64 takes up 8 bytes.
#Choosing the appropriate data type can save memory, especially when dealing with large datasets

#2.Performance:
#The choice of data type can also impact performance.
#Operations on smaller data types can be faster due to reduced memory bandwidth requirements and cache usage.

In [31]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists

#ndarrays>> n dimensional array


#Key Features of ndarrays
#Homogeneous Data
#Multi-dimensional:
#Fixed Size
#Efficient Memory Usage
#Fast Operationss 


#Differences from Standard Python Lists

#in ndarray all the data must be homogenous , but in python lists it can be any data type
# in ndarray numerical computations are faster , but in lists it is slower
#in ndarrays more memory-efficient due to contiguous storage and fixed size , but Python Lists: More memory overhead since they store references to objects and can dynamically resize.



In [1]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

#NumPy arrays offer several performance benefits over Python lists, 
# especially for large-scale numerical operations. Here are the key advantages:

# Memory Efficiency
#Performance and Speed
#Convenient Functions and Operations
#Parallelization
#Integration with Other Libraries



In [4]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

#In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally
#Example of vstack():

import numpy as np

a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

result_vstack = np.vstack((a1, a2))

print("Result of vstack:")
print(result_vstack)


Result of vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
#Example of hstack():

result_hstack = np.hstack((a1, a2))

print("Result of hstack:")
print(result_hstack)


Result of hstack:
[[1 2 5 6]
 [3 4 7 8]]


In [10]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions

#fliplr(): Flips arrays horizontally (left to right).
#flipud(): Flips arrays vertically (up to down).

#1D Arrays:
#Both functions effectively reverse the array in 1D array
#ex:

array_1d = np.array([[1, 2, 3, 4]])
print(np.fliplr(array_1d))  

[[4 3 2 1]]


In [11]:
#Higher-Dimensional Arrays:

array_3d = np.array([[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]]])

print("Flipping left to right:")
print(np.fliplr(array_3d))

print("\nFlipping up to down:")
print(np.flipud(array_3d))

Flipping left to right:
[[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]

Flipping up to down:
[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


In [14]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#array_split() is useful for dividing arrays into a specified number of sections,
#allowing for uneven splits when necessary.

#array_split() can also be applied to multi-dimensional arrays by specifying the axis along which to split:


array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

split_2d = np.array_split(array_2d, 2, axis=0)

split_2d

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [15]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
#operations?

#Vectorization refers to the ability to perform operations on entire arrays 
# or large blocks of data at once, rather than using explicit loops in Python.


#Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes and sizes.
#  When performing operations between two arrays, 
# NumPy automatically expands the smaller array to match the shape of the larger one, following specific rules.

#Together, these concepts contribute significantly to the efficiency of array operations in NumPy, 
# making it a powerful tool for numerical computing and data analysis.





In [28]:
                                                     #PRACTICAL QUESTIONS

# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

A = np.array(np.random.randint (1,100,(3,3)) )

In [30]:
A

array([[41, 57, 77],
       [91, 91, 68],
       [31, 38, 41]], dtype=int32)

In [31]:
A.T

array([[41, 91, 31],
       [57, 91, 38],
       [77, 68, 41]], dtype=int32)

In [33]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

array_1D = np.array([1,2,3,4,5,6,7,8,9,10])

In [35]:
array_1D.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
array_1D.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [84]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


array_4x4 = np.array(np.random.rand(4,4))
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

In [85]:
array_6x6

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.50633003, 0.52866749, 0.80569607, 0.35980047,
        0.        ],
       [0.        , 0.33499204, 0.84063313, 0.75096541, 0.50437796,
        0.        ],
       [0.        , 0.30228275, 0.86103142, 0.0383436 , 0.77324364,
        0.        ],
       [0.        , 0.33871265, 0.0189229 , 0.64991361, 0.86096471,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [91]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5


array = np.array(np.arange(10,60,5))

In [92]:
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [94]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
#(uppercase, lowercase, title case, etc.) to each element

array11 =  np.array(['python', 'numpy','pandas'])


In [97]:
np.char.upper(array11)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [98]:
np.char.lower(array11)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [99]:
np.char.capitalize(array11)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [100]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

words = np.array(["Abhay","Virat kohli","Darshan","pw"])

spaced_words = np.array([' '.join(word) for word in words])

print("Original array of words:")
print(words)

print("\nArray with spaces between characters:")
print(spaced_words)


Original array of words:
['Abhay' 'Virat kohli' 'Darshan' 'pw']

Array with spaces between characters:
['A b h a y' 'V i r a t   k o h l i' 'D a r s h a n' 'p w']


In [104]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

a = np.array([[1,2,3,4,5]])
b = np.array([[6,7,8,9,10]])


In [105]:
a+b

array([[ 7,  9, 11, 13, 15]])

In [106]:
a-b

array([[-5, -5, -5, -5, -5]])

In [107]:
a*b

array([[ 6, 14, 24, 36, 50]])

In [108]:
a/b

array([[0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]])

In [110]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

array_5x5 = np.eye(5)

In [113]:
array_5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [123]:
array_5x5[0,0] , array_5x5[1,1] ,array_5x5[2,2] , array_5x5[3,3] ,array_5x5[4,4]


(np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0))

In [130]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
#this array

arr = np.random.randint(1,1001,100 )

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True


prime_numbers = [num for num in arr if is_prime(num)]


print("Random integers:")
print(arr)

print("\nPrime numbers in the array:")
print(prime_numbers)


Random integers:
[503 104  61 606 120 781 979 964 607 265 521  46 761 718 554 854 776 107
 922 762 563 562 352 336 112 816 858 959 322  79 455 374 311 647 331 567
 599 441 854 131 188 416 557 917 584 976  54 810 303 108 317 782 861 524
 405 529  72 204 551 250 523 595 823 970 400  25 316 589 243 597 827 573
 600 310 940 633  58 378 807 366 343 679 734 148 127  95 615 655 891 860
 282 153 482 589 345 628 195 636 199 773]

Prime numbers in the array:
[np.int32(503), np.int32(61), np.int32(607), np.int32(521), np.int32(761), np.int32(107), np.int32(563), np.int32(79), np.int32(311), np.int32(647), np.int32(331), np.int32(599), np.int32(131), np.int32(557), np.int32(317), np.int32(523), np.int32(823), np.int32(827), np.int32(127), np.int32(199), np.int32(773)]


In [132]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
#averages


daily_temperatures = np.random.randint(15, 31, size=30)

weekly_temperatures = daily_temperatures.reshape(3,10)

weekly_averages = np.mean(weekly_temperatures, axis=1)


print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
for i, avg in enumerate(weekly_averages, start=1):
    print(f"Week {i}: {avg:.2f} °C")


Daily Temperatures for the Month:
[24 21 16 16 23 26 20 17 15 19 27 16 16 17 21 15 18 28 15 30 30 17 28 20
 18 21 15 26 26 18]

Weekly Averages:
Week 1: 19.70 °C
Week 2: 20.30 °C
Week 3: 21.90 °C
